services:
  rails:
    build: ./
    container_name: backend-frogmi
    ports:
      - "3000:3000"    
  react:
    build: ./client
    container_name: frontend-frogmi
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://rails:3000/api/v1/features/